language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "pypy"
    - python: "pypy3.5"
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install six requests"
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script: "pytest --cov=easypost --cov-report=term-missing tests/"
