language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install six requests"
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script: "pytest --cov=easypost --cov-report=term-missing tests/"
